### ISSUE TITLE
No notation for new sefer in Tehillim / empty column C

### ISSUE THREAD

**Issue by awes12** [bdenckla/MAM-parsed#2]
There is nothing in the tehillim "plus" file noting where new sefarim of tehillim start. The google sheets has 2 pseudo-verses (תתת, etc.), but there isn't even a newline in the JSON file, or even a space.
Furthermore, there are 17 places (including the above) in the plus folder where column C (index 0) is empty (I can give a list if you want), which probably is a mistake.

**Comment by bdenckla** [comment]
Thank you for reporting this issue, @awes12. In Wikisource MAM, there are template calls that I think will serve your needs: calls to the מ:רווח לספר בתהלים template. There are 5 such calls (ever) and the calls have an argument indicating the start of a [sub-]book of Psalms, e.g.:

- {{מ:רווח לספר בתהלים|ספר ראשון}}
- ...
- {{מ:רווח לספר בתהלים|ספר חמישי}}

BUT ...

Somehow I have managed to erase those template calls from the Google sources of MAM. And the "MAM-parsed" editions (both "plain" and "plus" varieties) come from the Google sources of MAM, not from the Wikisource sources of MAM.

So, unless this was intentional (I'll try to figure that out), this is a bug. I suspect that this is the result of my "auto-edits" process gone wild. The auto-edits process is the process that updates the MAM Google Sheet with changes from MAM sources on Wikisource. As the saying goes: "To err is human, but to really screw things up requires a computer." I.e. I suspect these erasures were automated, not manual.

I do see that I have code to explicitly drop calls to the מ:רווח לספר בתהלים template from the "plus" variety of MAM-parsed, so once I fix this issue, i.e. once I restore מ:רווח לספר בתהלים to "plain", we can address that question separately: whether perhaps calls to that template should be preserved in "plus" rather than dropped.

When that is all done I hope to then separately address the (potential) bug(s) you have flagged, where there are 17 suspiciously-blank cells in the C column.

So the plan of attack is:

- restore מ:רווח לספר בתהלים to Google sources (and therefore to MAM-parsed-plain)
- possibly change policy to preserve rather than drop מ:רווח לספר בתהלים from MAM-parsed-plus
- investigate those 17 suspiciously-blank cells in the C column of MAM-parsed-plus

I may create separate issues for each of these; we'll see.

**Comment by bdenckla** [comment]
BTW, @awes12, if you're willing, please contact me privately (e.g. Twitter direct message) to let me know a little more about how you are using (or plan to use) MAM. I'm just curious. (My email address is unfortunately already out there "in the wild" on the Internet but I figure I shouldn't compound the problem by putting it here.)

**Comment by bdenckla** [comment]
Closing this issue since all of its 3 parts are now represented by their own individual issues. Two of those three parts are now done, by the way.

- #3
- #4
- #5
